// src/layouts/shared/data.js
import { FileText, HomeIcon, ShieldCheck } from "lucide-react";

const features = [
    {
        icon: FileText,
        title: "Amplia gama de propiedades",
        desc: "Ofrecemos asistencia legal especializada para todo lo relacionado con la propiedad en Colombia.",
    },
    {
        icon: HomeIcon,
        title: "Comprar o alquilar casas",
        desc: "Vendemos tu casa al mejor precio del mercado y además con mucha rapidez.",
    },
    {
        icon: ShieldCheck,
        title: "Con la confianza de miles de personas",
        desc: "Te ofrecemos asesoría gratuita para obtener un préstamo para tu nueva vivienda.",
    }
];

export default features;

export const properties = [
  {
    id: 1,
    imagen: "https://res.cloudinary.com/dmc8ifonk/image/upload/v1750914433/imagenes_publicas/m9jfryzef2g7h3qsuhwv.jpg",
    titulo: "Villa One Hyde Park",
    ubicacion: "Carepa, Colombia",
    precio: 120000,
    habitaciones: 4,
    banos: 2,
    area: 350,
    tipo: "casa",
    estado: "venta",
    ciudad: "Carepa"
  },
  {
    id: 2,
    imagen: "https://images.unsplash.com/photo-1506744038136-46273834b3fb",
    titulo: "Apartamento Central Park",
    ubicacion: "Medellín, Colombia",
    precio: 95000,
    habitaciones: 3,
    banos: 2,
    area: 120,
    tipo: "apartamento",
    estado: "arriendo",
    ciudad: "Medellín"
  },
  {
    id: 3,
    imagen: "https://images.unsplash.com/photo-1460518451285-97b6aa326961",
    titulo: "Oficina Skyline",
    ubicacion: "Bogotá, Colombia",
    precio: 200000,
    habitaciones: 0,
    banos: 2,
    area: 500,
    tipo: "oficina",
    estado: "venta",
    ciudad: "Bogotá"
  },
  {
    id: 4,
    imagen: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae",
    titulo: "Hotel Boutique Sol",
    ubicacion: "Cartagena, Colombia",
    precio: 350000,
    habitaciones: 10,
    banos: 12,
    area: 1200,
    tipo: "hotel",
    estado: "arriendo",
    ciudad: "Cartagena"
  },
  {
    id: 5,
    imagen: "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd",
    titulo: "Casa Familiar Campestre",
    ubicacion: "Rionegro, Colombia",
    precio: 180000,
    habitaciones: 5,
    banos: 4,
    area: 600,
    tipo: "casa",
    estado: "venta",
    ciudad: "Rionegro"
  },
  {
    id: 6,
    imagen: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca",
    titulo: "Residencia El Lago",
    ubicacion: "Envigado, Colombia",
    precio: 210000,
    habitaciones: 5,
    banos: 3,
    area: 420,
    tipo: "casa",
    estado: "venta",
    ciudad: "Envigado"
  },
  {
    id: 7,
    imagen: "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
    titulo: "Apartamento Vista Verde",
    ubicacion: "Bucaramanga, Colombia",
    precio: 80000,
    habitaciones: 2,
    banos: 1,
    area: 90,
    tipo: "apartamento",
    estado: "arriendo",
    ciudad: "Bucaramanga"
  },
  {
    id: 8,
    imagen: "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd",
    titulo: "Casa Colonial",
    ubicacion: "Santa Marta, Colombia",
    precio: 160000,
    habitaciones: 4,
    banos: 3,
    area: 350,
    tipo: "casa",
    estado: "venta",
    ciudad: "Santa Marta"
  },
  {
    id: 9,
    imagen: "https://images.unsplash.com/photo-1464983953574-0892a716854b",
    titulo: "Oficina Business Center",
    ubicacion: "Cali, Colombia",
    precio: 250000,
    habitaciones: 0,
    banos: 2,
    area: 600,
    tipo: "oficina",
    estado: "arriendo",
    ciudad: "Cali"
  },
  {
    id: 10,
    imagen: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae",
    titulo: "Hotel Mar Azul",
    ubicacion: "San Andrés, Colombia",
    precio: 400000,
    habitaciones: 15,
    banos: 18,
    area: 2000,
    tipo: "hotel",
    estado: "venta",
    ciudad: "San Andrés"
  },
  {
    id: 11,
    imagen: "https://images.unsplash.com/photo-1465101178521-c1a9136a3b99",
    titulo: "Apartamento Moderno",
    ubicacion: "Pereira, Colombia",
    precio: 110000,
    habitaciones: 3,
    banos: 2,
    area: 110,
    tipo: "apartamento",
    estado: "venta",
    ciudad: "Pereira"
  },
  {
    id: 12,
    imagen: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca",
    titulo: "Casa Campestre",
    ubicacion: "Manizales, Colombia",
    precio: 195000,
    habitaciones: 4,
    banos: 3,
    area: 500,
    tipo: "casa",
    estado: "arriendo",
    ciudad: "Manizales"
  },
  {
    id: 13,
    imagen: "https://images.unsplash.com/photo-1506744038136-46273834b3fb",
    titulo: "Apartamento Central",
    ubicacion: "Barranquilla, Colombia",
    precio: 90000,
    habitaciones: 2,
    banos: 2,
    area: 95,
    tipo: "apartamento",
    estado: "arriendo",
    ciudad: "Barranquilla"
  },
  {
    id: 14,
    imagen: "https://images.unsplash.com/photo-1460518451285-97b6aa326961",
    titulo: "Oficina Ejecutiva",
    ubicacion: "Bogotá, Colombia",
    precio: 300000,
    habitaciones: 0,
    banos: 3,
    area: 800,
    tipo: "oficina",
    estado: "venta",
    ciudad: "Bogotá"
  },
  {
    id: 15,
    imagen: "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd",
    titulo: "Casa de Playa",
    ubicacion: "Cartagena, Colombia",
    precio: 350000,
    habitaciones: 6,
    banos: 5,
    area: 900,
    tipo: "casa",
    estado: "venta",
    ciudad: "Cartagena"
  },
  {
    id: 16,
    imagen: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae",
    titulo: "Hotel Sol Caribe",
    ubicacion: "Santa Marta, Colombia",
    precio: 420000,
    habitaciones: 20,
    banos: 22,
    area: 2500,
    tipo: "hotel",
    estado: "arriendo",
    ciudad: "Santa Marta"
  },
  {
    id: 17,
    imagen: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca",
    titulo: "Casa Jardín",
    ubicacion: "Cúcuta, Colombia",
    precio: 175000,
    habitaciones: 4,
    banos: 3,
    area: 380,
    tipo: "casa",
    estado: "venta",
    ciudad: "Cúcuta"
  },
  {
    id: 18,
    imagen: "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
    titulo: "Apartamento Urbano",
    ubicacion: "Ibagué, Colombia",
    precio: 105000,
    habitaciones: 3,
    banos: 2,
    area: 100,
    tipo: "apartamento",
    estado: "arriendo",
    ciudad: "Ibagué"
  },
  {
    id: 19,
    imagen: "https://images.unsplash.com/photo-1464983953574-0892a716854b",
    titulo: "Oficina Prime",
    ubicacion: "Villavicencio, Colombia",
    precio: 220000,
    habitaciones: 0,
    banos: 2,
    area: 450,
    tipo: "oficina",
    estado: "venta",
    ciudad: "Villavicencio"
  },
  {
    id: 20,
    imagen: "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd",
    titulo: "Casa Moderna",
    ubicacion: "Neiva, Colombia",
    precio: 185000,
    habitaciones: 5,
    banos: 4,
    area: 520,
    tipo: "casa",
    estado: "arriendo",
    ciudad: "Neiva"
  },
  {
    id: 21,
    imagen: "https://images.unsplash.com/photo-1465101178521-c1a9136a3b99",
    titulo: "Apartamento Familiar",
    ubicacion: "Popayán, Colombia",
    precio: 99000,
    habitaciones: 3,
    banos: 2,
    area: 105,
    tipo: "apartamento",
    estado: "venta",
    ciudad: "Popayán"
  },
  {
    id: 22,
    imagen: "https://images.unsplash.com/photo-1506744038136-46273834b3fb",
    titulo: "Apartamento Loft",
    ubicacion: "Tunja, Colombia",
    precio: 87000,
    habitaciones: 2,
    banos: 1,
    area: 80,
    tipo: "apartamento",
    estado: "arriendo",
    ciudad: "Tunja"
  },
  {
    id: 23,
    imagen: "https://images.unsplash.com/photo-1460518451285-97b6aa326961",
    titulo: "Oficina Centro",
    ubicacion: "Pasto, Colombia",
    precio: 160000,
    habitaciones: 0,
    banos: 1,
    area: 300,
    tipo: "oficina",
    estado: "arriendo",
    ciudad: "Pasto"
  },
  {
    id: 24,
    imagen: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca",
    titulo: "Casa Esquinera",
    ubicacion: "Montería, Colombia",
    precio: 140000,
    habitaciones: 3,
    banos: 2,
    area: 250,
    tipo: "casa",
    estado: "venta",
    ciudad: "Montería"
  },
  {
    id: 25,
    imagen: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae",
    titulo: "Hotel Boutique Plaza",
    ubicacion: "Leticia, Colombia",
    precio: 370000,
    habitaciones: 12,
    banos: 14,
    area: 1500,
    tipo: "hotel",
    estado: "venta",
    ciudad: "Leticia"
  }
];